require "favicon_maker/maker_config"
require "favicon_maker/generator"
require "favicon_maker/creator"
require "favicon_maker/base_command"
require "favicon_maker/ico_command"
require "favicon_maker/png_command"
require "favicon_maker/input_validator"
