require "favicon_maker/maker_config"
require "favicon_maker/input_validator"
require "favicon_maker/generator"
require "favicon_maker/creator"
require "favicon_maker/commands/base_command"
require "favicon_maker/commands/ico_command"
require "favicon_maker/commands/png_command"
